### ISSUE TITLE
4 hours windows being 3.5 hours ??

### ISSUE THREAD

**Issue by pattdepanick** [HewlettPackard/HackShack-Session-Landing-Page#189]
It seems that we are saying that the time allocation for a given workshop is  4 hours wher in reality it is shorter.

Vincent Berger and Patrick Francois have witnessed this behavior.
Customer registration occurs at 9.00 am. Reminder email is sent 11.30 and final email at 12.30.

Could you check your time mechanism ? 

![time4hours](https://user-images.githubusercontent.com/25387895/122195684-de01ac80-ce96-11eb-89f0-02d5e2523784.png)

**Comment by jaygiang** [comment]
This has been implemented in the following PR: https://github.com/HewlettPackard/HackShack-Session-Landing-Page/pull/239
