### ISSUE TITLE
Add new column in DB to allow Workshop Duration Change

### ISSUE THREAD

**Issue by pattdepanick** [HewlettPackard/HackShack-Session-Landing-Page#224]
By default all workshops offer a 4 hours windows timeframe  to be performed. 
Nwe usecasse :  Event Timetable limits The windows to less than 4 hours
The MASE 2021 summit will take place in october (mid october)
The Workshops sessions timetable allows only 2 hours timeframe per workshops
Either we change globally all workshops to a 2 hours timeframe during this event week
Or we change the code in the registration portal to allow a per workshop allocation time:
=> Possible impacts :
* Emails sent to customers that refer to a given workshop duration (Harcoded 4 hours in the text I believe for now)
* Flow of email : Unchanged last but one an hour before the end...
* Automation scripts in the backend : need to check (FP)

Request is to allow more flexibility in workshops duration to cope with  events requirements.

Second possibility :  Offer the user a possibility to end his workshop on his own : Add a button in the emails  to end workshop now . 
Message : You have completed your workshop and are willing to take another one ? Free your current seat by clicking on the following "End Workshop Now" button.
The button should change the end date of the workshop to the current date and time so that automation discovers it and automate cleanup and reset scripts as well as final emails.

**Comment by jaygiang** [comment]
This has been implemented in the following PRs: 
- https://github.com/HewlettPackard/HackShack-Session-Landing-Page/pull/239
- https://github.com/hpe-dev-incubator/workshops_on_demand_server/pull/32
