### ISSUE TITLE
Buttons do not match designs on arcade and community pages

### ISSUE THREAD

**Issue by IanKBovard** [HewlettPackard/HackShack-Session-Landing-Page#34]
![Screen Shot 2020-06-08 at 10 25 11 AM](https://user-images.githubusercontent.com/21990914/84049692-5b383e80-a972-11ea-9f79-9c263ec095cd.png)

**Comment by reddypramod85** [comment]
I have changed these buttons to secondary in the PR where we had a merge conflict

**Comment by IanKBovard** [comment]
changed them back
