### ISSUE TITLE
Make sure all copy is final

### ISSUE THREAD

**Issue by IanKBovard** [HewlettPackard/HackShack-Session-Landing-Page#35]

**Comment by reddypramod85** [comment]
Modify Didier role
Fix Nanda role
Remove HackShack from title's

**Comment by reddypramod85** [comment]
copy document in SharePoint [here](https://hpe.sharepoint.com/:w:/r/teams/hpe-design/_layouts/15/Doc.aspx?sourcedoc=%7B61665311-A8FD-4F8B-8F7E-0717F435F0DA%7D&file=Hack%20Shack%20Lobby%20Application%20Content%20and%20Links.docx&action=default&mobileredirect=true)
