### ISSUE TITLE
Firefox mobile view menu opener

### ISSUE THREAD

**Issue by reddypramod85** [HewlettPackard/HackShack-Session-Landing-Page#47]
On Menu opener - content overlaps with background image

![Screen Shot 2020-06-08 at 2 38 11 PM](https://user-images.githubusercontent.com/12749370/84073118-d8c17600-a995-11ea-94c3-ae6250247214.png)

**Comment by IanKBovard** [comment]
the problem is backdrop-filter: blur(15px);

**Comment by IanKBovard** [comment]
pr coming up
