### ISSUE TITLE
Edge browser home page issue

### ISSUE THREAD

**Issue by reddypramod85** [HewlettPackard/HackShack-Session-Landing-Page#53]
![image](https://user-images.githubusercontent.com/12749370/84153341-5daa9f00-aa2b-11ea-8cda-e57ea5630a7a.png)

**Comment by reddypramod85** [comment]
Latest on edge

![image](https://user-images.githubusercontent.com/12749370/85601819-57fcae00-b614-11ea-9481-a091fea577bd.png)

**Comment by IanKBovard** [comment]
latest version of edge solves this issue
